---
# tasks file for stefanhorning.ubuntu_hetzner_cloud

# -- State detection part --

# Settings that match a freshly brought up Hetzner Ubuntu image (SSH user: root, SSH port: 22)
- name: Set fact to run role tasks as root user (will be overriden below if custom user already exists)
  set_fact:
    ansible_ssh_user: root
    ansible_port: 22

- name: SSH ping with root user
  ping:
  ignore_errors: true
  ignore_unreachable: true
  register: root_user_ping

- name: Debug out
  debug:
    var: root_user_ping

# Settings tht match a instance this role has already run against (SSH user: hetzner_cloud_custom_user, SSH port: hetzner_cloud_ssh_port)
- name: Set SSH user {{ hetzner_cloud_custom_user }} on a rerun of this role (if connection with root credenials failed)
  set_fact:
    ansible_ssh_user: "{{ hetzner_cloud_custom_user }}"
    ansible_port: "{{ hetzner_cloud_ssh_port }}"
  when:
    - root_user_ping.unreachable is defined
    - root_user_ping.unreachable

# TODO: Also check for port reachability before assuming that SSHd conf has aleady been updated too.

- name: Gather facts with now correct SSH settings
  gather_facts:

- name: Output Linux OS version
  debug:
    msg: "Family: {{ ansible_os_family }} | Distro: {{ ansible_distribution }} | Version: {{ ansible_distribution_version }}"

- name: Output Python version that Ansible is currently using
  debug:
    var: ansible_python_version

- name: Output Ansible ssh user and port
  debug:
    msg: "ansible_ssh_user: {{ ansible_ssh_user }} | ansible_port: {{ ansible_port }}"

# -- APT tasks part --

- name: Upgrade all installed apt packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes
  when: hetzner_cloud_update_apt|bool

- name: Install useful apt packages
  become: true
  apt:
    name: "{{ hetzner_cloud_essential_packages }}"
    state: present

- name: Run apt clean-ups
  become: true
  apt:
    autoremove: true
    autoclean: true
  when: hetzner_cloud_update_apt|bool

# -- Custom user setup part (with sudo) --

- name: Make sure we have a wheel group for sudoing
  become: true
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    state: present

- name: Setup custom system user
  become: true
  user:
    name: "{{ hetzner_cloud_custom_user }}"
    shell: /bin/bash
    comment: Admin User
    create_home: true
    append: yes
    groups: wheel
    state: present

- name: Make sure .ssh dir exists for custom user
  file:
    path: /home/{{ hetzner_cloud_custom_user }}/.ssh/
    state: directory
    owner: "{{ hetzner_cloud_custom_user }}"
    group: "{{ hetzner_cloud_custom_user }}"
    mode: 0700

- name: Move public ssh keys from root user to custom user (when running as root)
  copy:
    remote_src: true
    src: /root/.ssh/authorized_keys
    dest: /home/{{ hetzner_cloud_custom_user }}/.ssh/authorized_keys
    owner: "{{ hetzner_cloud_custom_user }}"
    group: "{{ hetzner_cloud_custom_user }}"
    mode: 0600
  when: ansible_ssh_user == 'root'

# -- SSH config hardening/modifying part --

- name: Update SSH config to disallow root login
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: Update SSH config to disallow password auth
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Update SSH config to use custom port
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^Port'
    line: 'Port {{ hetzner_cloud_ssh_port }}'
    state: present

# -- Firewall setup part (block all incomming ports except whitelisted) --

- name: Install UFW firewall
  become: true
  apt:
    name: ufw
    state: present

- name: Set UFW rule to deny incomming traffic by default
  become: true
  ufw:
    direction: incoming
    default: deny

- name: Set UFW rule to allow outgoing traffic by default
  become: true
  ufw:
    direction: outgoing
    default: allow

- name: Ensure configured SSH port is still opened UFW
  become: true
  ufw:
    rule: allow
    port: "{{ hetzner_cloud_ssh_port }}"
    proto: tcp

- name: Add other ports to allow incomming traffic from
  become: true
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
  with_items: "{{ hetzner_cloud_open_ports }}"

# -- Restart and apply above settings (SSHd, Firewall) --

- name: Restart SSHd server to switch to new port (use new port and user after this)
  become: true
  service:
    name: sshd
    state: restarted
    enabled: true

- name: Output infos
  debug:
    msg: Now use {{ hetzner_cloud_custom_user }} and port {{ hetzner_cloud_ssh_port }} to SSH to machine now (remaining role tasks do this automatically)

- name: Set new Ansible SSH port
  set_fact:
    ansible_port: "{{ hetzner_cloud_ssh_port }}"

- name: Enable Firewall rules (only allows whitelisted ports after this)
  become: true
  ufw:
    state: enabled
  register: ufw_results

- name: Output UWF results
  debug:
    var: ufw_results

